-- Create word_analysis table
CREATE TABLE public.word_analysis (
    id bigint generated by default as identity primary key,
    created_at timestamp with time zone not null default now(),
    word text not null,
    source_language text not null,
    target_language text not null,
    analysis jsonb null,
    constraint word_analysis_unique unique (word, source_language, target_language)
);

-- Enable RLS
ALTER TABLE public.word_analysis ENABLE ROW LEVEL SECURITY;

-- Allow public read access
CREATE POLICY "Allow public read access for word_analysis"
ON public.word_analysis
FOR SELECT
USING (true);

-- Allow service_role to insert (used by edge function)
CREATE POLICY "Allow service_role to insert for word_analysis"
ON public.word_analysis
FOR INSERT
WITH CHECK (false); -- This policy will not match for users, only for service role